# Generated by Django 3.2.4 on 2021-11-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='nota1',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota 1'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='nota2',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota 2'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='nota3',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota 3'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='nota4',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota 4'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='nota5',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota 5'),
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='nota6',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Nota 6'),
        ),
        migrations.AlterField(
            model_name='programas',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=50, verbose_name='Indicar estado disponible o no disponible'),
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut postulante')),
                ('postulante', models.CharField(max_length=200, verbose_name='Nombre del postulante')),
                ('fechaNaci', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
                ('estadoCivil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Separado', 'Separado'), ('Viudo', 'Viudo'), ('Otro', 'Otro')], default='Soltero', max_length=50, verbose_name='Estado civil')),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Masculino', max_length=50, verbose_name='Indicar sexo')),
                ('telefono', models.IntegerField(verbose_name='Numero de celular')),
                ('correo', models.CharField(max_length=200, verbose_name='Correo del postulante')),
                ('procAcademica', models.CharField(max_length=200, verbose_name='Procedencia academica')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programas')),
            ],
        ),
    ]
